### PR TITLE
Adding Javascript and CSS style Mobile menu

### PR DESCRIPTION
**Pull request by lerfast**
Hi, I did the following task:

- [ ] Open a new repository.
- [ ] Open New Branch
- [ ] put Portfolio files into new branch
- [ ] Add Javascript function to popup menu in mobile portfolio
- [ ] Put CSS styles to mobile menu pop up

### CODE REVIEW

**Review by didierganthier — COMMENTED** [review]
Hi Team,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.



## Invalid Code Review Request 🚫

- You have submitted a project that doesn't have the JavaScript linters setup. You should set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) Linters in the project repository. You can follow the instructions [here](https://github.com/microverseinc/linters-config/tree/master/html-css-js) for that. 📖 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

**Comment by lerfast** [comment]
Can you help me with the styles? I tried everything but nothing works, can you please help me?

**Review by zainsadaqat — APPROVED** [review]
# Pull Request Approved ✅ 🎊 🎉 
## Hello @lerfast and @didierganthier 👋 
### [Optional]

- [ ] To keep the design consistent, Please make sure the hamburger and cross icons are in the same position to increase accessibility. 👍 

#### Hamburger Icon

Screenshot 2023-04-12 at 1 54 16 AM

#### Cross Icon

Screenshot 2023-04-12 at 1 55 00 AM


## Things to Appreciate 
- [ ] Correct Flow ✅ 
- [ ] Clean Code 👍 
- [ ] No Linter Errors 🔥 
- [ ] Descriptive Pull Request and Summary 👌 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by didierganthier** [comment]
@zainsadaqat I was a reviewer on this 😂

**Pull request merged**
